[project]
name = "fast-mcp-cerbos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cerbos>=0.14.0",
    "fastmcp>=2.12.3"
]
